/*
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define RCC_CR_OFFSET		0x00UL
#define RCC_BASE_ADDR		0x40023800UL
#define RCC_CFGR_OFFSET		0x08UL

int main(void) {
	// 1. enable HSE clock with RCC_CR
	uint32_t *pRccCrRegAddr = (uint32_t*) (RCC_BASE_ADDR + RCC_CR_OFFSET);
	*pRccCrRegAddr |= (1 << 16);   // set the HSEON bit to 1

	// 2. wait till HSE clock is ready
	while (!(*pRccCrRegAddr & (1 << 17))) {
	};

	// 3.switch system clock to HSE with RCC_CFGR
	uint32_t *pRccCfgrRegAddr = (uint32_t*) (RCC_BASE_ADDR + RCC_CFGR_OFFSET);
	*pRccCfgrRegAddr |= (1 << 0);   // set the SW bit to 1

	// 4. measure and test - needs logic analyzer

	/* Loop forever */
	for (;;) {
	};
}
