################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: local
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../drivers/Src/stm32l4xx_hal.c \
../drivers/Src/stm32l4xx_hal_adc.c \
../drivers/Src/stm32l4xx_hal_adc_ex.c \
../drivers/Src/stm32l4xx_hal_can.c \
../drivers/Src/stm32l4xx_hal_comp.c \
../drivers/Src/stm32l4xx_hal_cortex.c \
../drivers/Src/stm32l4xx_hal_crc.c \
../drivers/Src/stm32l4xx_hal_crc_ex.c \
../drivers/Src/stm32l4xx_hal_cryp.c \
../drivers/Src/stm32l4xx_hal_cryp_ex.c \
../drivers/Src/stm32l4xx_hal_dac.c \
../drivers/Src/stm32l4xx_hal_dac_ex.c \
../drivers/Src/stm32l4xx_hal_dcmi.c \
../drivers/Src/stm32l4xx_hal_dfsdm.c \
../drivers/Src/stm32l4xx_hal_dfsdm_ex.c \
../drivers/Src/stm32l4xx_hal_dma.c \
../drivers/Src/stm32l4xx_hal_dma2d.c \
../drivers/Src/stm32l4xx_hal_dma_ex.c \
../drivers/Src/stm32l4xx_hal_dsi.c \
../drivers/Src/stm32l4xx_hal_exti.c \
../drivers/Src/stm32l4xx_hal_firewall.c \
../drivers/Src/stm32l4xx_hal_flash.c \
../drivers/Src/stm32l4xx_hal_flash_ex.c \
../drivers/Src/stm32l4xx_hal_flash_ramfunc.c \
../drivers/Src/stm32l4xx_hal_gfxmmu.c \
../drivers/Src/stm32l4xx_hal_gpio.c \
../drivers/Src/stm32l4xx_hal_hash.c \
../drivers/Src/stm32l4xx_hal_hash_ex.c \
../drivers/Src/stm32l4xx_hal_hcd.c \
../drivers/Src/stm32l4xx_hal_i2c.c \
../drivers/Src/stm32l4xx_hal_i2c_ex.c \
../drivers/Src/stm32l4xx_hal_irda.c \
../drivers/Src/stm32l4xx_hal_iwdg.c \
../drivers/Src/stm32l4xx_hal_lcd.c \
../drivers/Src/stm32l4xx_hal_lptim.c \
../drivers/Src/stm32l4xx_hal_ltdc.c \
../drivers/Src/stm32l4xx_hal_ltdc_ex.c \
../drivers/Src/stm32l4xx_hal_mmc.c \
../drivers/Src/stm32l4xx_hal_mmc_ex.c \
../drivers/Src/stm32l4xx_hal_msp_template.c \
../drivers/Src/stm32l4xx_hal_nand.c \
../drivers/Src/stm32l4xx_hal_nor.c \
../drivers/Src/stm32l4xx_hal_opamp.c \
../drivers/Src/stm32l4xx_hal_opamp_ex.c \
../drivers/Src/stm32l4xx_hal_ospi.c \
../drivers/Src/stm32l4xx_hal_pcd.c \
../drivers/Src/stm32l4xx_hal_pcd_ex.c \
../drivers/Src/stm32l4xx_hal_pka.c \
../drivers/Src/stm32l4xx_hal_pssi.c \
../drivers/Src/stm32l4xx_hal_pwr.c \
../drivers/Src/stm32l4xx_hal_pwr_ex.c \
../drivers/Src/stm32l4xx_hal_qspi.c \
../drivers/Src/stm32l4xx_hal_rcc.c \
../drivers/Src/stm32l4xx_hal_rcc_ex.c \
../drivers/Src/stm32l4xx_hal_rng.c \
../drivers/Src/stm32l4xx_hal_rng_ex.c \
../drivers/Src/stm32l4xx_hal_rtc.c \
../drivers/Src/stm32l4xx_hal_rtc_ex.c \
../drivers/Src/stm32l4xx_hal_sai.c \
../drivers/Src/stm32l4xx_hal_sai_ex.c \
../drivers/Src/stm32l4xx_hal_sd.c \
../drivers/Src/stm32l4xx_hal_sd_ex.c \
../drivers/Src/stm32l4xx_hal_smartcard.c \
../drivers/Src/stm32l4xx_hal_smartcard_ex.c \
../drivers/Src/stm32l4xx_hal_smbus.c \
../drivers/Src/stm32l4xx_hal_smbus_ex.c \
../drivers/Src/stm32l4xx_hal_spi.c \
../drivers/Src/stm32l4xx_hal_spi_ex.c \
../drivers/Src/stm32l4xx_hal_sram.c \
../drivers/Src/stm32l4xx_hal_swpmi.c \
../drivers/Src/stm32l4xx_hal_tim.c \
../drivers/Src/stm32l4xx_hal_tim_ex.c \
../drivers/Src/stm32l4xx_hal_timebase_tim_template.c \
../drivers/Src/stm32l4xx_hal_tsc.c \
../drivers/Src/stm32l4xx_hal_uart.c \
../drivers/Src/stm32l4xx_hal_uart_ex.c \
../drivers/Src/stm32l4xx_hal_usart.c \
../drivers/Src/stm32l4xx_hal_usart_ex.c \
../drivers/Src/stm32l4xx_hal_wwdg.c \
../drivers/Src/stm32l4xx_ll_adc.c \
../drivers/Src/stm32l4xx_ll_comp.c \
../drivers/Src/stm32l4xx_ll_crc.c \
../drivers/Src/stm32l4xx_ll_crs.c \
../drivers/Src/stm32l4xx_ll_dac.c \
../drivers/Src/stm32l4xx_ll_dma.c \
../drivers/Src/stm32l4xx_ll_dma2d.c \
../drivers/Src/stm32l4xx_ll_exti.c \
../drivers/Src/stm32l4xx_ll_fmc.c \
../drivers/Src/stm32l4xx_ll_gpio.c \
../drivers/Src/stm32l4xx_ll_i2c.c \
../drivers/Src/stm32l4xx_ll_lptim.c \
../drivers/Src/stm32l4xx_ll_lpuart.c \
../drivers/Src/stm32l4xx_ll_opamp.c \
../drivers/Src/stm32l4xx_ll_pka.c \
../drivers/Src/stm32l4xx_ll_pwr.c \
../drivers/Src/stm32l4xx_ll_rcc.c \
../drivers/Src/stm32l4xx_ll_rng.c \
../drivers/Src/stm32l4xx_ll_rtc.c \
../drivers/Src/stm32l4xx_ll_sdmmc.c \
../drivers/Src/stm32l4xx_ll_spi.c \
../drivers/Src/stm32l4xx_ll_swpmi.c \
../drivers/Src/stm32l4xx_ll_tim.c \
../drivers/Src/stm32l4xx_ll_usart.c \
../drivers/Src/stm32l4xx_ll_usb.c \
../drivers/Src/stm32l4xx_ll_utils.c 

OBJS += \
./drivers/Src/stm32l4xx_hal.o \
./drivers/Src/stm32l4xx_hal_adc.o \
./drivers/Src/stm32l4xx_hal_adc_ex.o \
./drivers/Src/stm32l4xx_hal_can.o \
./drivers/Src/stm32l4xx_hal_comp.o \
./drivers/Src/stm32l4xx_hal_cortex.o \
./drivers/Src/stm32l4xx_hal_crc.o \
./drivers/Src/stm32l4xx_hal_crc_ex.o \
./drivers/Src/stm32l4xx_hal_cryp.o \
./drivers/Src/stm32l4xx_hal_cryp_ex.o \
./drivers/Src/stm32l4xx_hal_dac.o \
./drivers/Src/stm32l4xx_hal_dac_ex.o \
./drivers/Src/stm32l4xx_hal_dcmi.o \
./drivers/Src/stm32l4xx_hal_dfsdm.o \
./drivers/Src/stm32l4xx_hal_dfsdm_ex.o \
./drivers/Src/stm32l4xx_hal_dma.o \
./drivers/Src/stm32l4xx_hal_dma2d.o \
./drivers/Src/stm32l4xx_hal_dma_ex.o \
./drivers/Src/stm32l4xx_hal_dsi.o \
./drivers/Src/stm32l4xx_hal_exti.o \
./drivers/Src/stm32l4xx_hal_firewall.o \
./drivers/Src/stm32l4xx_hal_flash.o \
./drivers/Src/stm32l4xx_hal_flash_ex.o \
./drivers/Src/stm32l4xx_hal_flash_ramfunc.o \
./drivers/Src/stm32l4xx_hal_gfxmmu.o \
./drivers/Src/stm32l4xx_hal_gpio.o \
./drivers/Src/stm32l4xx_hal_hash.o \
./drivers/Src/stm32l4xx_hal_hash_ex.o \
./drivers/Src/stm32l4xx_hal_hcd.o \
./drivers/Src/stm32l4xx_hal_i2c.o \
./drivers/Src/stm32l4xx_hal_i2c_ex.o \
./drivers/Src/stm32l4xx_hal_irda.o \
./drivers/Src/stm32l4xx_hal_iwdg.o \
./drivers/Src/stm32l4xx_hal_lcd.o \
./drivers/Src/stm32l4xx_hal_lptim.o \
./drivers/Src/stm32l4xx_hal_ltdc.o \
./drivers/Src/stm32l4xx_hal_ltdc_ex.o \
./drivers/Src/stm32l4xx_hal_mmc.o \
./drivers/Src/stm32l4xx_hal_mmc_ex.o \
./drivers/Src/stm32l4xx_hal_msp_template.o \
./drivers/Src/stm32l4xx_hal_nand.o \
./drivers/Src/stm32l4xx_hal_nor.o \
./drivers/Src/stm32l4xx_hal_opamp.o \
./drivers/Src/stm32l4xx_hal_opamp_ex.o \
./drivers/Src/stm32l4xx_hal_ospi.o \
./drivers/Src/stm32l4xx_hal_pcd.o \
./drivers/Src/stm32l4xx_hal_pcd_ex.o \
./drivers/Src/stm32l4xx_hal_pka.o \
./drivers/Src/stm32l4xx_hal_pssi.o \
./drivers/Src/stm32l4xx_hal_pwr.o \
./drivers/Src/stm32l4xx_hal_pwr_ex.o \
./drivers/Src/stm32l4xx_hal_qspi.o \
./drivers/Src/stm32l4xx_hal_rcc.o \
./drivers/Src/stm32l4xx_hal_rcc_ex.o \
./drivers/Src/stm32l4xx_hal_rng.o \
./drivers/Src/stm32l4xx_hal_rng_ex.o \
./drivers/Src/stm32l4xx_hal_rtc.o \
./drivers/Src/stm32l4xx_hal_rtc_ex.o \
./drivers/Src/stm32l4xx_hal_sai.o \
./drivers/Src/stm32l4xx_hal_sai_ex.o \
./drivers/Src/stm32l4xx_hal_sd.o \
./drivers/Src/stm32l4xx_hal_sd_ex.o \
./drivers/Src/stm32l4xx_hal_smartcard.o \
./drivers/Src/stm32l4xx_hal_smartcard_ex.o \
./drivers/Src/stm32l4xx_hal_smbus.o \
./drivers/Src/stm32l4xx_hal_smbus_ex.o \
./drivers/Src/stm32l4xx_hal_spi.o \
./drivers/Src/stm32l4xx_hal_spi_ex.o \
./drivers/Src/stm32l4xx_hal_sram.o \
./drivers/Src/stm32l4xx_hal_swpmi.o \
./drivers/Src/stm32l4xx_hal_tim.o \
./drivers/Src/stm32l4xx_hal_tim_ex.o \
./drivers/Src/stm32l4xx_hal_timebase_tim_template.o \
./drivers/Src/stm32l4xx_hal_tsc.o \
./drivers/Src/stm32l4xx_hal_uart.o \
./drivers/Src/stm32l4xx_hal_uart_ex.o \
./drivers/Src/stm32l4xx_hal_usart.o \
./drivers/Src/stm32l4xx_hal_usart_ex.o \
./drivers/Src/stm32l4xx_hal_wwdg.o \
./drivers/Src/stm32l4xx_ll_adc.o \
./drivers/Src/stm32l4xx_ll_comp.o \
./drivers/Src/stm32l4xx_ll_crc.o \
./drivers/Src/stm32l4xx_ll_crs.o \
./drivers/Src/stm32l4xx_ll_dac.o \
./drivers/Src/stm32l4xx_ll_dma.o \
./drivers/Src/stm32l4xx_ll_dma2d.o \
./drivers/Src/stm32l4xx_ll_exti.o \
./drivers/Src/stm32l4xx_ll_fmc.o \
./drivers/Src/stm32l4xx_ll_gpio.o \
./drivers/Src/stm32l4xx_ll_i2c.o \
./drivers/Src/stm32l4xx_ll_lptim.o \
./drivers/Src/stm32l4xx_ll_lpuart.o \
./drivers/Src/stm32l4xx_ll_opamp.o \
./drivers/Src/stm32l4xx_ll_pka.o \
./drivers/Src/stm32l4xx_ll_pwr.o \
./drivers/Src/stm32l4xx_ll_rcc.o \
./drivers/Src/stm32l4xx_ll_rng.o \
./drivers/Src/stm32l4xx_ll_rtc.o \
./drivers/Src/stm32l4xx_ll_sdmmc.o \
./drivers/Src/stm32l4xx_ll_spi.o \
./drivers/Src/stm32l4xx_ll_swpmi.o \
./drivers/Src/stm32l4xx_ll_tim.o \
./drivers/Src/stm32l4xx_ll_usart.o \
./drivers/Src/stm32l4xx_ll_usb.o \
./drivers/Src/stm32l4xx_ll_utils.o 

C_DEPS += \
./drivers/Src/stm32l4xx_hal.d \
./drivers/Src/stm32l4xx_hal_adc.d \
./drivers/Src/stm32l4xx_hal_adc_ex.d \
./drivers/Src/stm32l4xx_hal_can.d \
./drivers/Src/stm32l4xx_hal_comp.d \
./drivers/Src/stm32l4xx_hal_cortex.d \
./drivers/Src/stm32l4xx_hal_crc.d \
./drivers/Src/stm32l4xx_hal_crc_ex.d \
./drivers/Src/stm32l4xx_hal_cryp.d \
./drivers/Src/stm32l4xx_hal_cryp_ex.d \
./drivers/Src/stm32l4xx_hal_dac.d \
./drivers/Src/stm32l4xx_hal_dac_ex.d \
./drivers/Src/stm32l4xx_hal_dcmi.d \
./drivers/Src/stm32l4xx_hal_dfsdm.d \
./drivers/Src/stm32l4xx_hal_dfsdm_ex.d \
./drivers/Src/stm32l4xx_hal_dma.d \
./drivers/Src/stm32l4xx_hal_dma2d.d \
./drivers/Src/stm32l4xx_hal_dma_ex.d \
./drivers/Src/stm32l4xx_hal_dsi.d \
./drivers/Src/stm32l4xx_hal_exti.d \
./drivers/Src/stm32l4xx_hal_firewall.d \
./drivers/Src/stm32l4xx_hal_flash.d \
./drivers/Src/stm32l4xx_hal_flash_ex.d \
./drivers/Src/stm32l4xx_hal_flash_ramfunc.d \
./drivers/Src/stm32l4xx_hal_gfxmmu.d \
./drivers/Src/stm32l4xx_hal_gpio.d \
./drivers/Src/stm32l4xx_hal_hash.d \
./drivers/Src/stm32l4xx_hal_hash_ex.d \
./drivers/Src/stm32l4xx_hal_hcd.d \
./drivers/Src/stm32l4xx_hal_i2c.d \
./drivers/Src/stm32l4xx_hal_i2c_ex.d \
./drivers/Src/stm32l4xx_hal_irda.d \
./drivers/Src/stm32l4xx_hal_iwdg.d \
./drivers/Src/stm32l4xx_hal_lcd.d \
./drivers/Src/stm32l4xx_hal_lptim.d \
./drivers/Src/stm32l4xx_hal_ltdc.d \
./drivers/Src/stm32l4xx_hal_ltdc_ex.d \
./drivers/Src/stm32l4xx_hal_mmc.d \
./drivers/Src/stm32l4xx_hal_mmc_ex.d \
./drivers/Src/stm32l4xx_hal_msp_template.d \
./drivers/Src/stm32l4xx_hal_nand.d \
./drivers/Src/stm32l4xx_hal_nor.d \
./drivers/Src/stm32l4xx_hal_opamp.d \
./drivers/Src/stm32l4xx_hal_opamp_ex.d \
./drivers/Src/stm32l4xx_hal_ospi.d \
./drivers/Src/stm32l4xx_hal_pcd.d \
./drivers/Src/stm32l4xx_hal_pcd_ex.d \
./drivers/Src/stm32l4xx_hal_pka.d \
./drivers/Src/stm32l4xx_hal_pssi.d \
./drivers/Src/stm32l4xx_hal_pwr.d \
./drivers/Src/stm32l4xx_hal_pwr_ex.d \
./drivers/Src/stm32l4xx_hal_qspi.d \
./drivers/Src/stm32l4xx_hal_rcc.d \
./drivers/Src/stm32l4xx_hal_rcc_ex.d \
./drivers/Src/stm32l4xx_hal_rng.d \
./drivers/Src/stm32l4xx_hal_rng_ex.d \
./drivers/Src/stm32l4xx_hal_rtc.d \
./drivers/Src/stm32l4xx_hal_rtc_ex.d \
./drivers/Src/stm32l4xx_hal_sai.d \
./drivers/Src/stm32l4xx_hal_sai_ex.d \
./drivers/Src/stm32l4xx_hal_sd.d \
./drivers/Src/stm32l4xx_hal_sd_ex.d \
./drivers/Src/stm32l4xx_hal_smartcard.d \
./drivers/Src/stm32l4xx_hal_smartcard_ex.d \
./drivers/Src/stm32l4xx_hal_smbus.d \
./drivers/Src/stm32l4xx_hal_smbus_ex.d \
./drivers/Src/stm32l4xx_hal_spi.d \
./drivers/Src/stm32l4xx_hal_spi_ex.d \
./drivers/Src/stm32l4xx_hal_sram.d \
./drivers/Src/stm32l4xx_hal_swpmi.d \
./drivers/Src/stm32l4xx_hal_tim.d \
./drivers/Src/stm32l4xx_hal_tim_ex.d \
./drivers/Src/stm32l4xx_hal_timebase_tim_template.d \
./drivers/Src/stm32l4xx_hal_tsc.d \
./drivers/Src/stm32l4xx_hal_uart.d \
./drivers/Src/stm32l4xx_hal_uart_ex.d \
./drivers/Src/stm32l4xx_hal_usart.d \
./drivers/Src/stm32l4xx_hal_usart_ex.d \
./drivers/Src/stm32l4xx_hal_wwdg.d \
./drivers/Src/stm32l4xx_ll_adc.d \
./drivers/Src/stm32l4xx_ll_comp.d \
./drivers/Src/stm32l4xx_ll_crc.d \
./drivers/Src/stm32l4xx_ll_crs.d \
./drivers/Src/stm32l4xx_ll_dac.d \
./drivers/Src/stm32l4xx_ll_dma.d \
./drivers/Src/stm32l4xx_ll_dma2d.d \
./drivers/Src/stm32l4xx_ll_exti.d \
./drivers/Src/stm32l4xx_ll_fmc.d \
./drivers/Src/stm32l4xx_ll_gpio.d \
./drivers/Src/stm32l4xx_ll_i2c.d \
./drivers/Src/stm32l4xx_ll_lptim.d \
./drivers/Src/stm32l4xx_ll_lpuart.d \
./drivers/Src/stm32l4xx_ll_opamp.d \
./drivers/Src/stm32l4xx_ll_pka.d \
./drivers/Src/stm32l4xx_ll_pwr.d \
./drivers/Src/stm32l4xx_ll_rcc.d \
./drivers/Src/stm32l4xx_ll_rng.d \
./drivers/Src/stm32l4xx_ll_rtc.d \
./drivers/Src/stm32l4xx_ll_sdmmc.d \
./drivers/Src/stm32l4xx_ll_spi.d \
./drivers/Src/stm32l4xx_ll_swpmi.d \
./drivers/Src/stm32l4xx_ll_tim.d \
./drivers/Src/stm32l4xx_ll_usart.d \
./drivers/Src/stm32l4xx_ll_usb.d \
./drivers/Src/stm32l4xx_ll_utils.d 


# Each subdirectory must supply rules for building sources it contributes
drivers/Src/%.o drivers/Src/%.su drivers/Src/%.cyclo: ../drivers/Src/%.c drivers/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DSTM32L4 -DSTM32 -DB_L475E_IOT01A1 -DSTM32L475VGTx -c -I../Inc -I"/home/athul-muralidhar/Mastering-Microcontroller-and-Embedded-Driver-Development/stm32lxx_spi_slave/drivers/Inc" -I"/home/athul-muralidhar/Mastering-Microcontroller-and-Embedded-Driver-Development/stm32lxx_spi_slave/drivers/Src" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-drivers-2f-Src

clean-drivers-2f-Src:
	-$(RM) ./drivers/Src/stm32l4xx_hal.cyclo ./drivers/Src/stm32l4xx_hal.d ./drivers/Src/stm32l4xx_hal.o ./drivers/Src/stm32l4xx_hal.su ./drivers/Src/stm32l4xx_hal_adc.cyclo ./drivers/Src/stm32l4xx_hal_adc.d ./drivers/Src/stm32l4xx_hal_adc.o ./drivers/Src/stm32l4xx_hal_adc.su ./drivers/Src/stm32l4xx_hal_adc_ex.cyclo ./drivers/Src/stm32l4xx_hal_adc_ex.d ./drivers/Src/stm32l4xx_hal_adc_ex.o ./drivers/Src/stm32l4xx_hal_adc_ex.su ./drivers/Src/stm32l4xx_hal_can.cyclo ./drivers/Src/stm32l4xx_hal_can.d ./drivers/Src/stm32l4xx_hal_can.o ./drivers/Src/stm32l4xx_hal_can.su ./drivers/Src/stm32l4xx_hal_comp.cyclo ./drivers/Src/stm32l4xx_hal_comp.d ./drivers/Src/stm32l4xx_hal_comp.o ./drivers/Src/stm32l4xx_hal_comp.su ./drivers/Src/stm32l4xx_hal_cortex.cyclo ./drivers/Src/stm32l4xx_hal_cortex.d ./drivers/Src/stm32l4xx_hal_cortex.o ./drivers/Src/stm32l4xx_hal_cortex.su ./drivers/Src/stm32l4xx_hal_crc.cyclo ./drivers/Src/stm32l4xx_hal_crc.d ./drivers/Src/stm32l4xx_hal_crc.o ./drivers/Src/stm32l4xx_hal_crc.su ./drivers/Src/stm32l4xx_hal_crc_ex.cyclo ./drivers/Src/stm32l4xx_hal_crc_ex.d ./drivers/Src/stm32l4xx_hal_crc_ex.o ./drivers/Src/stm32l4xx_hal_crc_ex.su ./drivers/Src/stm32l4xx_hal_cryp.cyclo ./drivers/Src/stm32l4xx_hal_cryp.d ./drivers/Src/stm32l4xx_hal_cryp.o ./drivers/Src/stm32l4xx_hal_cryp.su ./drivers/Src/stm32l4xx_hal_cryp_ex.cyclo ./drivers/Src/stm32l4xx_hal_cryp_ex.d ./drivers/Src/stm32l4xx_hal_cryp_ex.o ./drivers/Src/stm32l4xx_hal_cryp_ex.su ./drivers/Src/stm32l4xx_hal_dac.cyclo ./drivers/Src/stm32l4xx_hal_dac.d ./drivers/Src/stm32l4xx_hal_dac.o ./drivers/Src/stm32l4xx_hal_dac.su ./drivers/Src/stm32l4xx_hal_dac_ex.cyclo ./drivers/Src/stm32l4xx_hal_dac_ex.d ./drivers/Src/stm32l4xx_hal_dac_ex.o ./drivers/Src/stm32l4xx_hal_dac_ex.su ./drivers/Src/stm32l4xx_hal_dcmi.cyclo ./drivers/Src/stm32l4xx_hal_dcmi.d ./drivers/Src/stm32l4xx_hal_dcmi.o ./drivers/Src/stm32l4xx_hal_dcmi.su ./drivers/Src/stm32l4xx_hal_dfsdm.cyclo ./drivers/Src/stm32l4xx_hal_dfsdm.d ./drivers/Src/stm32l4xx_hal_dfsdm.o ./drivers/Src/stm32l4xx_hal_dfsdm.su ./drivers/Src/stm32l4xx_hal_dfsdm_ex.cyclo ./drivers/Src/stm32l4xx_hal_dfsdm_ex.d ./drivers/Src/stm32l4xx_hal_dfsdm_ex.o ./drivers/Src/stm32l4xx_hal_dfsdm_ex.su ./drivers/Src/stm32l4xx_hal_dma.cyclo ./drivers/Src/stm32l4xx_hal_dma.d ./drivers/Src/stm32l4xx_hal_dma.o ./drivers/Src/stm32l4xx_hal_dma.su ./drivers/Src/stm32l4xx_hal_dma2d.cyclo ./drivers/Src/stm32l4xx_hal_dma2d.d ./drivers/Src/stm32l4xx_hal_dma2d.o ./drivers/Src/stm32l4xx_hal_dma2d.su ./drivers/Src/stm32l4xx_hal_dma_ex.cyclo ./drivers/Src/stm32l4xx_hal_dma_ex.d ./drivers/Src/stm32l4xx_hal_dma_ex.o ./drivers/Src/stm32l4xx_hal_dma_ex.su ./drivers/Src/stm32l4xx_hal_dsi.cyclo ./drivers/Src/stm32l4xx_hal_dsi.d ./drivers/Src/stm32l4xx_hal_dsi.o ./drivers/Src/stm32l4xx_hal_dsi.su ./drivers/Src/stm32l4xx_hal_exti.cyclo ./drivers/Src/stm32l4xx_hal_exti.d ./drivers/Src/stm32l4xx_hal_exti.o ./drivers/Src/stm32l4xx_hal_exti.su ./drivers/Src/stm32l4xx_hal_firewall.cyclo ./drivers/Src/stm32l4xx_hal_firewall.d ./drivers/Src/stm32l4xx_hal_firewall.o ./drivers/Src/stm32l4xx_hal_firewall.su ./drivers/Src/stm32l4xx_hal_flash.cyclo ./drivers/Src/stm32l4xx_hal_flash.d ./drivers/Src/stm32l4xx_hal_flash.o ./drivers/Src/stm32l4xx_hal_flash.su ./drivers/Src/stm32l4xx_hal_flash_ex.cyclo ./drivers/Src/stm32l4xx_hal_flash_ex.d ./drivers/Src/stm32l4xx_hal_flash_ex.o ./drivers/Src/stm32l4xx_hal_flash_ex.su ./drivers/Src/stm32l4xx_hal_flash_ramfunc.cyclo ./drivers/Src/stm32l4xx_hal_flash_ramfunc.d ./drivers/Src/stm32l4xx_hal_flash_ramfunc.o ./drivers/Src/stm32l4xx_hal_flash_ramfunc.su ./drivers/Src/stm32l4xx_hal_gfxmmu.cyclo ./drivers/Src/stm32l4xx_hal_gfxmmu.d ./drivers/Src/stm32l4xx_hal_gfxmmu.o ./drivers/Src/stm32l4xx_hal_gfxmmu.su ./drivers/Src/stm32l4xx_hal_gpio.cyclo ./drivers/Src/stm32l4xx_hal_gpio.d ./drivers/Src/stm32l4xx_hal_gpio.o ./drivers/Src/stm32l4xx_hal_gpio.su ./drivers/Src/stm32l4xx_hal_hash.cyclo ./drivers/Src/stm32l4xx_hal_hash.d ./drivers/Src/stm32l4xx_hal_hash.o ./drivers/Src/stm32l4xx_hal_hash.su ./drivers/Src/stm32l4xx_hal_hash_ex.cyclo ./drivers/Src/stm32l4xx_hal_hash_ex.d ./drivers/Src/stm32l4xx_hal_hash_ex.o ./drivers/Src/stm32l4xx_hal_hash_ex.su ./drivers/Src/stm32l4xx_hal_hcd.cyclo ./drivers/Src/stm32l4xx_hal_hcd.d ./drivers/Src/stm32l4xx_hal_hcd.o ./drivers/Src/stm32l4xx_hal_hcd.su ./drivers/Src/stm32l4xx_hal_i2c.cyclo ./drivers/Src/stm32l4xx_hal_i2c.d ./drivers/Src/stm32l4xx_hal_i2c.o ./drivers/Src/stm32l4xx_hal_i2c.su ./drivers/Src/stm32l4xx_hal_i2c_ex.cyclo ./drivers/Src/stm32l4xx_hal_i2c_ex.d ./drivers/Src/stm32l4xx_hal_i2c_ex.o ./drivers/Src/stm32l4xx_hal_i2c_ex.su ./drivers/Src/stm32l4xx_hal_irda.cyclo ./drivers/Src/stm32l4xx_hal_irda.d ./drivers/Src/stm32l4xx_hal_irda.o ./drivers/Src/stm32l4xx_hal_irda.su ./drivers/Src/stm32l4xx_hal_iwdg.cyclo ./drivers/Src/stm32l4xx_hal_iwdg.d ./drivers/Src/stm32l4xx_hal_iwdg.o ./drivers/Src/stm32l4xx_hal_iwdg.su ./drivers/Src/stm32l4xx_hal_lcd.cyclo ./drivers/Src/stm32l4xx_hal_lcd.d ./drivers/Src/stm32l4xx_hal_lcd.o ./drivers/Src/stm32l4xx_hal_lcd.su ./drivers/Src/stm32l4xx_hal_lptim.cyclo ./drivers/Src/stm32l4xx_hal_lptim.d ./drivers/Src/stm32l4xx_hal_lptim.o ./drivers/Src/stm32l4xx_hal_lptim.su ./drivers/Src/stm32l4xx_hal_ltdc.cyclo ./drivers/Src/stm32l4xx_hal_ltdc.d ./drivers/Src/stm32l4xx_hal_ltdc.o ./drivers/Src/stm32l4xx_hal_ltdc.su ./drivers/Src/stm32l4xx_hal_ltdc_ex.cyclo ./drivers/Src/stm32l4xx_hal_ltdc_ex.d ./drivers/Src/stm32l4xx_hal_ltdc_ex.o ./drivers/Src/stm32l4xx_hal_ltdc_ex.su ./drivers/Src/stm32l4xx_hal_mmc.cyclo ./drivers/Src/stm32l4xx_hal_mmc.d ./drivers/Src/stm32l4xx_hal_mmc.o ./drivers/Src/stm32l4xx_hal_mmc.su ./drivers/Src/stm32l4xx_hal_mmc_ex.cyclo ./drivers/Src/stm32l4xx_hal_mmc_ex.d ./drivers/Src/stm32l4xx_hal_mmc_ex.o ./drivers/Src/stm32l4xx_hal_mmc_ex.su ./drivers/Src/stm32l4xx_hal_msp_template.cyclo ./drivers/Src/stm32l4xx_hal_msp_template.d ./drivers/Src/stm32l4xx_hal_msp_template.o ./drivers/Src/stm32l4xx_hal_msp_template.su
	-$(RM) ./drivers/Src/stm32l4xx_hal_nand.cyclo ./drivers/Src/stm32l4xx_hal_nand.d ./drivers/Src/stm32l4xx_hal_nand.o ./drivers/Src/stm32l4xx_hal_nand.su ./drivers/Src/stm32l4xx_hal_nor.cyclo ./drivers/Src/stm32l4xx_hal_nor.d ./drivers/Src/stm32l4xx_hal_nor.o ./drivers/Src/stm32l4xx_hal_nor.su ./drivers/Src/stm32l4xx_hal_opamp.cyclo ./drivers/Src/stm32l4xx_hal_opamp.d ./drivers/Src/stm32l4xx_hal_opamp.o ./drivers/Src/stm32l4xx_hal_opamp.su ./drivers/Src/stm32l4xx_hal_opamp_ex.cyclo ./drivers/Src/stm32l4xx_hal_opamp_ex.d ./drivers/Src/stm32l4xx_hal_opamp_ex.o ./drivers/Src/stm32l4xx_hal_opamp_ex.su ./drivers/Src/stm32l4xx_hal_ospi.cyclo ./drivers/Src/stm32l4xx_hal_ospi.d ./drivers/Src/stm32l4xx_hal_ospi.o ./drivers/Src/stm32l4xx_hal_ospi.su ./drivers/Src/stm32l4xx_hal_pcd.cyclo ./drivers/Src/stm32l4xx_hal_pcd.d ./drivers/Src/stm32l4xx_hal_pcd.o ./drivers/Src/stm32l4xx_hal_pcd.su ./drivers/Src/stm32l4xx_hal_pcd_ex.cyclo ./drivers/Src/stm32l4xx_hal_pcd_ex.d ./drivers/Src/stm32l4xx_hal_pcd_ex.o ./drivers/Src/stm32l4xx_hal_pcd_ex.su ./drivers/Src/stm32l4xx_hal_pka.cyclo ./drivers/Src/stm32l4xx_hal_pka.d ./drivers/Src/stm32l4xx_hal_pka.o ./drivers/Src/stm32l4xx_hal_pka.su ./drivers/Src/stm32l4xx_hal_pssi.cyclo ./drivers/Src/stm32l4xx_hal_pssi.d ./drivers/Src/stm32l4xx_hal_pssi.o ./drivers/Src/stm32l4xx_hal_pssi.su ./drivers/Src/stm32l4xx_hal_pwr.cyclo ./drivers/Src/stm32l4xx_hal_pwr.d ./drivers/Src/stm32l4xx_hal_pwr.o ./drivers/Src/stm32l4xx_hal_pwr.su ./drivers/Src/stm32l4xx_hal_pwr_ex.cyclo ./drivers/Src/stm32l4xx_hal_pwr_ex.d ./drivers/Src/stm32l4xx_hal_pwr_ex.o ./drivers/Src/stm32l4xx_hal_pwr_ex.su ./drivers/Src/stm32l4xx_hal_qspi.cyclo ./drivers/Src/stm32l4xx_hal_qspi.d ./drivers/Src/stm32l4xx_hal_qspi.o ./drivers/Src/stm32l4xx_hal_qspi.su ./drivers/Src/stm32l4xx_hal_rcc.cyclo ./drivers/Src/stm32l4xx_hal_rcc.d ./drivers/Src/stm32l4xx_hal_rcc.o ./drivers/Src/stm32l4xx_hal_rcc.su ./drivers/Src/stm32l4xx_hal_rcc_ex.cyclo ./drivers/Src/stm32l4xx_hal_rcc_ex.d ./drivers/Src/stm32l4xx_hal_rcc_ex.o ./drivers/Src/stm32l4xx_hal_rcc_ex.su ./drivers/Src/stm32l4xx_hal_rng.cyclo ./drivers/Src/stm32l4xx_hal_rng.d ./drivers/Src/stm32l4xx_hal_rng.o ./drivers/Src/stm32l4xx_hal_rng.su ./drivers/Src/stm32l4xx_hal_rng_ex.cyclo ./drivers/Src/stm32l4xx_hal_rng_ex.d ./drivers/Src/stm32l4xx_hal_rng_ex.o ./drivers/Src/stm32l4xx_hal_rng_ex.su ./drivers/Src/stm32l4xx_hal_rtc.cyclo ./drivers/Src/stm32l4xx_hal_rtc.d ./drivers/Src/stm32l4xx_hal_rtc.o ./drivers/Src/stm32l4xx_hal_rtc.su ./drivers/Src/stm32l4xx_hal_rtc_ex.cyclo ./drivers/Src/stm32l4xx_hal_rtc_ex.d ./drivers/Src/stm32l4xx_hal_rtc_ex.o ./drivers/Src/stm32l4xx_hal_rtc_ex.su ./drivers/Src/stm32l4xx_hal_sai.cyclo ./drivers/Src/stm32l4xx_hal_sai.d ./drivers/Src/stm32l4xx_hal_sai.o ./drivers/Src/stm32l4xx_hal_sai.su ./drivers/Src/stm32l4xx_hal_sai_ex.cyclo ./drivers/Src/stm32l4xx_hal_sai_ex.d ./drivers/Src/stm32l4xx_hal_sai_ex.o ./drivers/Src/stm32l4xx_hal_sai_ex.su ./drivers/Src/stm32l4xx_hal_sd.cyclo ./drivers/Src/stm32l4xx_hal_sd.d ./drivers/Src/stm32l4xx_hal_sd.o ./drivers/Src/stm32l4xx_hal_sd.su ./drivers/Src/stm32l4xx_hal_sd_ex.cyclo ./drivers/Src/stm32l4xx_hal_sd_ex.d ./drivers/Src/stm32l4xx_hal_sd_ex.o ./drivers/Src/stm32l4xx_hal_sd_ex.su ./drivers/Src/stm32l4xx_hal_smartcard.cyclo ./drivers/Src/stm32l4xx_hal_smartcard.d ./drivers/Src/stm32l4xx_hal_smartcard.o ./drivers/Src/stm32l4xx_hal_smartcard.su ./drivers/Src/stm32l4xx_hal_smartcard_ex.cyclo ./drivers/Src/stm32l4xx_hal_smartcard_ex.d ./drivers/Src/stm32l4xx_hal_smartcard_ex.o ./drivers/Src/stm32l4xx_hal_smartcard_ex.su ./drivers/Src/stm32l4xx_hal_smbus.cyclo ./drivers/Src/stm32l4xx_hal_smbus.d ./drivers/Src/stm32l4xx_hal_smbus.o ./drivers/Src/stm32l4xx_hal_smbus.su ./drivers/Src/stm32l4xx_hal_smbus_ex.cyclo ./drivers/Src/stm32l4xx_hal_smbus_ex.d ./drivers/Src/stm32l4xx_hal_smbus_ex.o ./drivers/Src/stm32l4xx_hal_smbus_ex.su ./drivers/Src/stm32l4xx_hal_spi.cyclo ./drivers/Src/stm32l4xx_hal_spi.d ./drivers/Src/stm32l4xx_hal_spi.o ./drivers/Src/stm32l4xx_hal_spi.su ./drivers/Src/stm32l4xx_hal_spi_ex.cyclo ./drivers/Src/stm32l4xx_hal_spi_ex.d ./drivers/Src/stm32l4xx_hal_spi_ex.o ./drivers/Src/stm32l4xx_hal_spi_ex.su ./drivers/Src/stm32l4xx_hal_sram.cyclo ./drivers/Src/stm32l4xx_hal_sram.d ./drivers/Src/stm32l4xx_hal_sram.o ./drivers/Src/stm32l4xx_hal_sram.su ./drivers/Src/stm32l4xx_hal_swpmi.cyclo ./drivers/Src/stm32l4xx_hal_swpmi.d ./drivers/Src/stm32l4xx_hal_swpmi.o ./drivers/Src/stm32l4xx_hal_swpmi.su ./drivers/Src/stm32l4xx_hal_tim.cyclo ./drivers/Src/stm32l4xx_hal_tim.d ./drivers/Src/stm32l4xx_hal_tim.o ./drivers/Src/stm32l4xx_hal_tim.su ./drivers/Src/stm32l4xx_hal_tim_ex.cyclo ./drivers/Src/stm32l4xx_hal_tim_ex.d ./drivers/Src/stm32l4xx_hal_tim_ex.o ./drivers/Src/stm32l4xx_hal_tim_ex.su ./drivers/Src/stm32l4xx_hal_timebase_tim_template.cyclo ./drivers/Src/stm32l4xx_hal_timebase_tim_template.d ./drivers/Src/stm32l4xx_hal_timebase_tim_template.o ./drivers/Src/stm32l4xx_hal_timebase_tim_template.su ./drivers/Src/stm32l4xx_hal_tsc.cyclo ./drivers/Src/stm32l4xx_hal_tsc.d ./drivers/Src/stm32l4xx_hal_tsc.o ./drivers/Src/stm32l4xx_hal_tsc.su ./drivers/Src/stm32l4xx_hal_uart.cyclo ./drivers/Src/stm32l4xx_hal_uart.d ./drivers/Src/stm32l4xx_hal_uart.o ./drivers/Src/stm32l4xx_hal_uart.su ./drivers/Src/stm32l4xx_hal_uart_ex.cyclo ./drivers/Src/stm32l4xx_hal_uart_ex.d ./drivers/Src/stm32l4xx_hal_uart_ex.o ./drivers/Src/stm32l4xx_hal_uart_ex.su ./drivers/Src/stm32l4xx_hal_usart.cyclo ./drivers/Src/stm32l4xx_hal_usart.d ./drivers/Src/stm32l4xx_hal_usart.o ./drivers/Src/stm32l4xx_hal_usart.su ./drivers/Src/stm32l4xx_hal_usart_ex.cyclo ./drivers/Src/stm32l4xx_hal_usart_ex.d ./drivers/Src/stm32l4xx_hal_usart_ex.o ./drivers/Src/stm32l4xx_hal_usart_ex.su ./drivers/Src/stm32l4xx_hal_wwdg.cyclo ./drivers/Src/stm32l4xx_hal_wwdg.d ./drivers/Src/stm32l4xx_hal_wwdg.o ./drivers/Src/stm32l4xx_hal_wwdg.su ./drivers/Src/stm32l4xx_ll_adc.cyclo ./drivers/Src/stm32l4xx_ll_adc.d ./drivers/Src/stm32l4xx_ll_adc.o
	-$(RM) ./drivers/Src/stm32l4xx_ll_adc.su ./drivers/Src/stm32l4xx_ll_comp.cyclo ./drivers/Src/stm32l4xx_ll_comp.d ./drivers/Src/stm32l4xx_ll_comp.o ./drivers/Src/stm32l4xx_ll_comp.su ./drivers/Src/stm32l4xx_ll_crc.cyclo ./drivers/Src/stm32l4xx_ll_crc.d ./drivers/Src/stm32l4xx_ll_crc.o ./drivers/Src/stm32l4xx_ll_crc.su ./drivers/Src/stm32l4xx_ll_crs.cyclo ./drivers/Src/stm32l4xx_ll_crs.d ./drivers/Src/stm32l4xx_ll_crs.o ./drivers/Src/stm32l4xx_ll_crs.su ./drivers/Src/stm32l4xx_ll_dac.cyclo ./drivers/Src/stm32l4xx_ll_dac.d ./drivers/Src/stm32l4xx_ll_dac.o ./drivers/Src/stm32l4xx_ll_dac.su ./drivers/Src/stm32l4xx_ll_dma.cyclo ./drivers/Src/stm32l4xx_ll_dma.d ./drivers/Src/stm32l4xx_ll_dma.o ./drivers/Src/stm32l4xx_ll_dma.su ./drivers/Src/stm32l4xx_ll_dma2d.cyclo ./drivers/Src/stm32l4xx_ll_dma2d.d ./drivers/Src/stm32l4xx_ll_dma2d.o ./drivers/Src/stm32l4xx_ll_dma2d.su ./drivers/Src/stm32l4xx_ll_exti.cyclo ./drivers/Src/stm32l4xx_ll_exti.d ./drivers/Src/stm32l4xx_ll_exti.o ./drivers/Src/stm32l4xx_ll_exti.su ./drivers/Src/stm32l4xx_ll_fmc.cyclo ./drivers/Src/stm32l4xx_ll_fmc.d ./drivers/Src/stm32l4xx_ll_fmc.o ./drivers/Src/stm32l4xx_ll_fmc.su ./drivers/Src/stm32l4xx_ll_gpio.cyclo ./drivers/Src/stm32l4xx_ll_gpio.d ./drivers/Src/stm32l4xx_ll_gpio.o ./drivers/Src/stm32l4xx_ll_gpio.su ./drivers/Src/stm32l4xx_ll_i2c.cyclo ./drivers/Src/stm32l4xx_ll_i2c.d ./drivers/Src/stm32l4xx_ll_i2c.o ./drivers/Src/stm32l4xx_ll_i2c.su ./drivers/Src/stm32l4xx_ll_lptim.cyclo ./drivers/Src/stm32l4xx_ll_lptim.d ./drivers/Src/stm32l4xx_ll_lptim.o ./drivers/Src/stm32l4xx_ll_lptim.su ./drivers/Src/stm32l4xx_ll_lpuart.cyclo ./drivers/Src/stm32l4xx_ll_lpuart.d ./drivers/Src/stm32l4xx_ll_lpuart.o ./drivers/Src/stm32l4xx_ll_lpuart.su ./drivers/Src/stm32l4xx_ll_opamp.cyclo ./drivers/Src/stm32l4xx_ll_opamp.d ./drivers/Src/stm32l4xx_ll_opamp.o ./drivers/Src/stm32l4xx_ll_opamp.su ./drivers/Src/stm32l4xx_ll_pka.cyclo ./drivers/Src/stm32l4xx_ll_pka.d ./drivers/Src/stm32l4xx_ll_pka.o ./drivers/Src/stm32l4xx_ll_pka.su ./drivers/Src/stm32l4xx_ll_pwr.cyclo ./drivers/Src/stm32l4xx_ll_pwr.d ./drivers/Src/stm32l4xx_ll_pwr.o ./drivers/Src/stm32l4xx_ll_pwr.su ./drivers/Src/stm32l4xx_ll_rcc.cyclo ./drivers/Src/stm32l4xx_ll_rcc.d ./drivers/Src/stm32l4xx_ll_rcc.o ./drivers/Src/stm32l4xx_ll_rcc.su ./drivers/Src/stm32l4xx_ll_rng.cyclo ./drivers/Src/stm32l4xx_ll_rng.d ./drivers/Src/stm32l4xx_ll_rng.o ./drivers/Src/stm32l4xx_ll_rng.su ./drivers/Src/stm32l4xx_ll_rtc.cyclo ./drivers/Src/stm32l4xx_ll_rtc.d ./drivers/Src/stm32l4xx_ll_rtc.o ./drivers/Src/stm32l4xx_ll_rtc.su ./drivers/Src/stm32l4xx_ll_sdmmc.cyclo ./drivers/Src/stm32l4xx_ll_sdmmc.d ./drivers/Src/stm32l4xx_ll_sdmmc.o ./drivers/Src/stm32l4xx_ll_sdmmc.su ./drivers/Src/stm32l4xx_ll_spi.cyclo ./drivers/Src/stm32l4xx_ll_spi.d ./drivers/Src/stm32l4xx_ll_spi.o ./drivers/Src/stm32l4xx_ll_spi.su ./drivers/Src/stm32l4xx_ll_swpmi.cyclo ./drivers/Src/stm32l4xx_ll_swpmi.d ./drivers/Src/stm32l4xx_ll_swpmi.o ./drivers/Src/stm32l4xx_ll_swpmi.su ./drivers/Src/stm32l4xx_ll_tim.cyclo ./drivers/Src/stm32l4xx_ll_tim.d ./drivers/Src/stm32l4xx_ll_tim.o ./drivers/Src/stm32l4xx_ll_tim.su ./drivers/Src/stm32l4xx_ll_usart.cyclo ./drivers/Src/stm32l4xx_ll_usart.d ./drivers/Src/stm32l4xx_ll_usart.o ./drivers/Src/stm32l4xx_ll_usart.su ./drivers/Src/stm32l4xx_ll_usb.cyclo ./drivers/Src/stm32l4xx_ll_usb.d ./drivers/Src/stm32l4xx_ll_usb.o ./drivers/Src/stm32l4xx_ll_usb.su ./drivers/Src/stm32l4xx_ll_utils.cyclo ./drivers/Src/stm32l4xx_ll_utils.d ./drivers/Src/stm32l4xx_ll_utils.o ./drivers/Src/stm32l4xx_ll_utils.su

.PHONY: clean-drivers-2f-Src

